### ISSUE TITLE
Docs not working on harlemjs.com

### ISSUE THREAD

**Issue by mgdodge** [andrewcourtice/harlem#14]
Very interested in looking at your library, but the docs link on harlemjs.com is broken.

**Comment by andrewcourtice** [comment]
Thanks @mgdodge - I'll get that fixed up and let you know once it's sorted. In the meantime the main readme in the repo should get you started and the api reference docs are available [here](https://github.com/andrewcourtice/harlem/tree/main/docs)

**Comment by w3bdesign** [comment]
@andrewcourtice 

This is still not working. Any update?

**Comment by andrewcourtice** [comment]
@mgdodge @w3bdesign 

Apologies for taking so long to get back to you about this. I have been migrating the documentation over to a VuePress application which is now deployed to https://harlemjs.com.

Some areas of the docs are a bit unfinished at this time but I will be continually working on them to ensure they are easy to follow.
