### ISSUE TITLE
Allow mutations to take multiple parameters

### ISSUE THREAD

**Issue by timbasel** [andrewcourtice/harlem#22]
I would like to be able to create mutations that can take multiple arguments. e.g.

```ts
import { createStore } from "@harlem/core";

const STATE = {
  map: new Map<string, string>(),
};

const { getter, mutation, ...state } = createStore("store", STATE);

const addItem = mutation("addItem", (state, key: string, value: string) => {
  state.map.set(key, value);
});

addItem("example", "harlem is awesome");
```

For my use case this would allow me to bind the first parameter to a fixed value and have a user button press set the `value`, without having to repeat the `key` every time.

I can't see any way/reason how this change would effect existing implementations, when e.g. implemented using the spread operator.

PS: thank you for generally awesome library

**Comment by andrewcourtice** [comment]
Hi @timbasel 

Thank you for your kind words.

The original motivation behind having a single payload argument was for a few reasons:
- Consistency - having a single argument means every mutation has the same form which (I feel) produces less side-effects
- Easier integration with TypeScript
- Easier to audit (eg. the devtools plugin)

That being said - I am still open to the idea, perhaps in a future update 👍

**Comment by timbasel** [comment]
Thank you for the quick reply,

having looked at the implementation it would definitely add quite a bit of complexity.
I solved my use case by a simple wrapper function, so the change is of no priority for me and I feel the current  simplicity is of more value for the library and the gained flexibility.
