### ISSUE TITLE
Loss of prototype when cloning payload in mutations

### ISSUE THREAD

**Issue by z0091** [andrewcourtice/harlem#36]
**HI!**

https://github.com/andrewcourtice/harlem/blob/f31c8478341f36cdbb1d10747d97e7c1f265e9ad/packages/utilities/src/object/clone.ts#L32-L41

In my opinion, copying objects in this way is not quite right. The fact is that this method of cloning leads to the loss of the prototype.

```TypeScript
class OrderItem {
    amount: number;
    id: number;

    item__name: string;
    options: [];

    @Transform(({ value }) => Money.of(value))
    price: Money;

    priceByQuantity(): Money {
        return Money.multiply(this.price, this.amount);
    }
}

setItemMutation(plainToClass(OrderItem, someRawData))

store.item.priceByQuantity() // there will be a runtime error
```

I solved the problem as follows:

```ts
import cloneDeep from 'lodash/cloneDeep';

export const { state, getter, mutation, action, ...store } = createStore(NAME, STATE, {
    extensions: [actionExtension()],
    providers: {
        read: (state) => state,
        write: (state) => state,
        payload: (payload) => cloneDeep(payload),
    },
});
```

Thanks!

**Comment by andrewcourtice** [comment]
Closing this issue as cloning prototypes would be considered an edge-case. Payload objects should be simple, disposable objects. Alternative workaround listed above using lodash to clone the prototype chain.
